version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: air_quality_kafka
    ports:
      - "9092:9092"
    environment:
      # Configure Kafka to listen both inside the Docker network and on your local machine
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,LOCAL://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,LOCAL://kafka:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # A pre-generated valid random UUID
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  fastapi_server:
      build: .
      container_name: air_quality_api
      ports:
        - "8000:8000"
      depends_on:
        - kafka

    # The streaming ML Scorer
  ml_consumer:
      build: .
      container_name: air_quality_consumer
      # Overrides the uvicorn command to run the consumer script
      command: ["python", "-m", "src.serving.kafka_consumer"]
      environment:
        # Tell the consumer to look for the dockerized kafka, not localhost
        - BOOTSTRAP_SERVERS=kafka:9092
      depends_on:
        - kafka

    # The mock sensor data generator
  sensor_producer:
      build: .
      container_name: air_quality_producer
      command: ["python", "-m", "src.serving.kafka_producer"]
      environment:
        - BOOTSTRAP_SERVERS=kafka:9092
      depends_on:
        - kafka